### ISSUE TITLE
_ssl.c:504: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime#104]
After upgrading requests from 2.13.0 to 2.18.4, this error appears when sending heartbeats:

```
Max retries exceeded with url: /api/v1/heartbeats (Caused by SSLError(SSLError(1, '_ssl.c:504: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm
```

First reported with wakatime/sublime-wakatime#78.

**Comment by tmharber** [comment]
Thanks for finding this - what's the current way to fix this?

**Comment by alanhamlett** [comment]
Another error message from Anaconda on Windows:

```
File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
wakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

**Comment by alanhamlett** [comment]
Possibly fixed with [v13.0.4 of wakatime](https://github.com/wakatime/wakatime/blob/master/HISTORY.rst#1304-2020-02-05).
